### PR TITLE
reverting annotation and adjust IIFE wrapper

### PR DESCRIPTION
**Pull request by avacollins**
Sorry I broke your build, I was having issues using the decorator in my app after minification, but it turns out that the issue was related to IIFE wrapper. It looks identical to what I replaced it with but somehow the replacement fixed the issue.

### CODE REVIEW

**Comment by insidewhy** [comment]
Don't worry about the break I should have noticed it was wrong!

**Comment by insidewhy** [comment]
Hi, this commit should fix the minifier compatibility:

https://github.com/ohjames/angular-promise-extras/commit/df1f80b0940535aaf77ec44d998b63cf08bd6a31

**Comment by avacollins** [comment]
Thanks for understanding, and nope semi colons not needed :)

**Comment by insidewhy** [comment]
There's too much hostility in the world of open source, we gotta be nice to each other! Let me know if that commit fixes your issue and I can push another release so you can download it via bower.

**Comment by avacollins** [comment]
You're p awesome. Thanks for fixing things are working now :+1:

**Pull request closed without merging**
