### PR TITLE
Support for angular 1.6

### PR DESCRIPTION
**Pull request by mtrias**
How does this look ?

### CODE REVIEW

**Comment by mtrias** [comment]
Also, in my local environment I had to add the "karma-chrome-launcher" dependency to be able to run the tests.

I'm not sure why that is not failing for others or for CI, but I could add it as well here if needed.

**Comment by mtrias** [comment]
Done

**Comment by insidewhy** [comment]
@mtrias I'm abandoning this project now as I've moved on to Angular 4 and no longer care about or use Angular 1.x, if you are still using it I can make you a maintainer.

**Comment by mtrias** [comment]
Oh, sad to see you go. Thanks for your work here! It saved us a bunch of lines :)

And yes, I'd be glad to be a maintainer. I'm still using AngularJS for my projects. Thanks!

**Comment by insidewhy** [comment]
@mtrias Cool thanks! After getting a taste for Angular 2/4 (and react/redux) I've decided to no longer accept angular 1.x contracts so I won't have any more need for this. Feel free to add all the semicolons you want. If only angular 1.x would let you configure the promise implementation. I really like bluebird. Since native promises landed everywhere you don't get to use bluebird so much and I miss it.

**Pull request merged**
